name: Validate PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
        - '**.md'
        - 'docs/**'

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: Validate code style
        run: dotnet format --verify-no-changes

      - name: 🔨 Build solution
        run: dotnet build -maxcpucount
    timeout-minutes: 3
